# Generated by Django 5.0 on 2023-12-10 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=50)),
                ("dob", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("mail_id", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("staff", "Staff"),
                            ("manager", "Manager"),
                            ("supervisor", "Supervisor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("performance", models.FloatField(default=60)),
                ("date_of_join", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("customer_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "product_category_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Duty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_cat", models.CharField(max_length=50)),
                ("work", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("time up", "Time Up"),
                        ],
                        max_length=50,
                    ),
                ),
                ("deadline", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAS_app.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("reason", models.CharField(max_length=50)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAS_app.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "inventory_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("in stock", "In Stock"),
                            ("have to add", "Have to Add"),
                            ("sold", "Sold"),
                        ],
                        max_length=50,
                    ),
                ),
                ("purchased_stock", models.IntegerField()),
                ("expiry", models.DateField()),
                ("stock_expense", models.DecimalField(decimal_places=2, max_digits=10)),
                ("other_expense", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField()),
                ("date_of_purchase", models.DateField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAS_app.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="product_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="SAS_app.productcategory",
            ),
        ),
        migrations.CreateModel(
            name="ProductItem",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("damaged", models.BooleanField()),
                ("sold", models.BooleanField()),
                ("verified", models.BooleanField()),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAS_app.inventory",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAS_app.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                ("return_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "product_item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAS_app.productitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("sale_id", models.IntegerField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="SAS_app.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAS_app.product",
                    ),
                ),
            ],
        ),
    ]
