# Generated by Django 5.0 on 2023-12-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_app", "0002_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="date_of_join",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="dob",
        ),
    ]
