# Generated by Django 5.0 on 2023-12-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_app", "0005_alter_productitem_damaged_alter_productitem_sold_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
