# Generated by Django 5.0 on 2023-12-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_app", "0009_alter_order_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="inventory_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
