# Generated by Django 5.0 on 2023-12-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_app", "0010_alter_inventory_inventory_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="product_category_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
