# Generated by Django 5.0 on 2023-12-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_app", "0011_alter_product_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duty",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("time up", "Time Up"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
