# Generated by Django 5.0 on 2023-12-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_app", "0012_alter_duty_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duty",
            name="staff_cat",
            field=models.CharField(default="staff", max_length=50),
        ),
    ]
