# Generated by Django 5.0 on 2023-12-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_app", "0013_alter_duty_staff_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
