# Generated by Django 5.0 on 2023-12-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_app", "0014_alter_employee_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
