# Generated by Django 5.0 on 2023-12-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_app", "0016_alter_productitem_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="damaged",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
