# Generated by Django 5.0 on 2023-12-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_app", "0018_alter_productitem_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
