# Generated by Django 5.0 on 2023-12-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SAS_app", "0023_alter_sale_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="order",
            field=models.ForeignKey(
                default=1000,
                on_delete=django.db.models.deletion.CASCADE,
                to="SAS_app.order",
            ),
        ),
    ]
